from pathlib import Path

from vylyv_forge.errors import ForgeError
from vylyv_forge.filesystem import create_file, create_init_file
from vylyv_forge.terminal import print_info, print_success
from vylyv_forge.requirements_manager import add_requirements_if_missing

def normalize_module_name(name: str) -> str:
    return name.strip().lower().replace("-", "_")


def validate_module_name(name: str) -> None:
    if not name or not name.strip():
        raise ForgeError("Module name cannot be empty.")

    normalized_name = normalize_module_name(name)

    if not normalized_name.isidentifier():
        raise ForgeError(
            "Invalid module name. Use only letters, numbers, and underscores. "
            "The name cannot start with a number."
        )


def ensure_project_structure(project_dir: Path) -> None:
    src_dir = project_dir / "src"

    if not src_dir.exists():
        raise ForgeError(
            "This does not look like a Python project generated by Forge. "
            "The src folder was not found."
        )

    modules_dir = src_dir / "modules"
    modules_dir.mkdir(parents=True, exist_ok=True)


def create_module(
    name: str,
    with_router: bool = False,
    with_tests: bool = False,
    crud: bool = False,
    update_requirements: bool = True,
) -> None:
    validate_module_name(name)

    module_name = normalize_module_name(name)
    project_dir = Path.cwd()

    ensure_project_structure(project_dir)

    module_dir = project_dir / "src" / "modules" / module_name

    if module_dir.exists():
        raise ForgeError(f"Module already exists: {module_name}")

    if update_requirements:
        dependencies = ["pydantic"]

        if with_router:
            dependencies.append("fastapi")

        if with_tests:
            dependencies.append("pytest")

        add_requirements_if_missing(project_dir, dependencies)

    print_info(f"Creating module: {module_name}")

    folders = [
        module_dir,
        module_dir / "dto",
        module_dir / "repository",
        module_dir / "service",
        module_dir / "validators",
    ]

    for folder in folders:
        create_init_file(folder)

    create_file(
        module_dir / "dto" / f"create_{module_name}_dto.py",
        f"""from pydantic import BaseModel

    


class Create{module_name.title().replace("_", "")}DTO(BaseModel):
    name: str
""",
    )

    create_file(
        module_dir / "validators" / f"{module_name}_validator.py",
        f"""from src.shared.errors.app_error import AppError


def validate_{module_name}_name(name: str) -> None:
    if not name or len(name.strip()) < 3:
        raise AppError("{module_name.title()} name must have at least 3 characters.")
""",
    )

    create_file(
        module_dir / "repository" / f"{module_name}_repository.py",
        f"""def find_all_{module_name}() -> list[dict]:
    return []
""",
    )

    create_file(
        module_dir / "service" / f"{module_name}_service.py",
        f"""from src.modules.{module_name}.dto.create_{module_name}_dto import Create{module_name.title().replace("_", "")}DTO
from src.modules.{module_name}.validators.{module_name}_validator import validate_{module_name}_name


def create_{module_name}(dto: Create{module_name.title().replace("_", "")}DTO) -> dict[str, str]:
    validate_{module_name}_name(dto.name)

    return {{
        "status": "created",
        "message": "{module_name.title()} creation flow is ready to be implemented.",
    }}
""",
    )

    if crud:
        create_file(
            module_dir / "service" / f"{module_name}_crud_service.py",
            f"""def list_{module_name}() -> list[dict]:
    return []


def get_{module_name}_by_id({module_name}_id: str) -> dict[str, str]:
    return {{
        "id": {module_name}_id,
        "message": "{module_name.title()} found.",
    }}


def update_{module_name}({module_name}_id: str) -> dict[str, str]:
    return {{
        "id": {module_name}_id,
        "message": "{module_name.title()} updated.",
    }}


def delete_{module_name}({module_name}_id: str) -> dict[str, str]:
    return {{
        "id": {module_name}_id,
        "message": "{module_name.title()} deleted.",
    }}
""",
        )

    if with_router:
        create_router(project_dir, module_name, crud)

    if with_tests:
        create_tests(project_dir, module_name)

    print_success(f"Module {module_name} created successfully.")

    if with_router:
        create_router(project_dir, module_name, crud)

    if with_tests:
        create_tests(project_dir, module_name)

    if update_requirements:
        dependencies = ["pydantic"]

        if with_router:
            dependencies.append("fastapi")

        if with_tests:
            dependencies.append("pytest")

        add_requirements_if_missing(project_dir, dependencies)

    print_success(f"Module {module_name} created successfully.")

def create_router(project_dir: Path, module_name: str, crud: bool) -> None:
    routers_dir = project_dir / "src" / "routers"
    routers_dir.mkdir(parents=True, exist_ok=True)

    if crud:
        content = f"""from fastapi import APIRouter

router = APIRouter(prefix="/{module_name}", tags=["{module_name}"])


@router.get("/")
def list_{module_name}() -> list[dict]:
    return []


@router.get("/{{item_id}}")
def get_{module_name}(item_id: str) -> dict[str, str]:
    return {{
        "id": item_id,
        "message": "{module_name.title()} found.",
    }}


@router.post("/")
def create_{module_name}() -> dict[str, str]:
    return {{
        "message": "{module_name.title()} created.",
    }}


@router.put("/{{item_id}}")
def update_{module_name}(item_id: str) -> dict[str, str]:
    return {{
        "id": item_id,
        "message": "{module_name.title()} updated.",
    }}


@router.delete("/{{item_id}}")
def delete_{module_name}(item_id: str) -> dict[str, str]:
    return {{
        "id": item_id,
        "message": "{module_name.title()} deleted.",
    }}
"""
    else:
        content = f"""from fastapi import APIRouter

router = APIRouter(prefix="/{module_name}", tags=["{module_name}"])


@router.get("/")
def list_{module_name}() -> list[dict]:
    return []
"""

    create_file(
        routers_dir / f"{module_name}_router.py",
        content,
    )


def create_tests(project_dir: Path, module_name: str) -> None:
    tests_dir = project_dir / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)

    create_file(
        tests_dir / f"test_{module_name}.py",
        f"""def test_{module_name}_example() -> None:
    assert True
""",
    )